modLoader="javafml"
loaderVersion="[40,)"
license="GNU GPL3"
[[mods]]
    modId="clocktower"
    version="18.2.1"
    displayName="Clock Tower"
    authors="skyjay1"
    description="I like big clocks"
[[dependencies.clocktower]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
