modLoader="javafml"
loaderVersion="[36,)"
license="GNU GPL3"
[[mods]]
    modId="clocktower"
    version="16.5.1"
    displayName="Clock Tower"
    authors="skyjay1"
    description="I like big clocks"
[[dependencies.clocktower]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
